@startuml

class Receiver {
    - name: String
    - phone: String
    - card: Int
}

class Country {
    - code: String
    - name: String
}

class Transfer {
    country: Country
    amount: BigDecimal
    commission: BigDecimal
    currency: String
    receiver: Receiver
}
Transfer o-- Country
Transfer o-- Receiver

class MainScreen {
    - createTransferButton: Button
}

class MainViewModel {
    - transfer: Transfer

    createTransfer()
    - chooseCountry(): Country
    - chooseReceiver(): Receiver
    - getCommission(): Money
    - signIn(): Status

}
MainScreen *-- MainViewModel
MainViewModel *-- Transfer
MainViewModel ..> "use" Country

class TransferRepository {
    + createTransfer(transfer: Transfer): Status
    + confirmTransfer(paymentId: String): String
    + getTransferId(): String
}
MainViewModel o-- TransferRepository

class PaymentCardViewModel {
    - transfer: Transfer
    + sendPayment(card: Card): Status
}
MainViewModel o-- PaymentCardViewModel
PaymentCardViewModel o-- Transfer

class PaymentCardRepository {
    + sendPaymentCard(card: Card, amount: BigDecimal): String
}
PaymentCardViewModel o-- PaymentCardRepository

package "Other Screens" <<Rectangle>> {
}
package "Other ViewModels" <<Rectangle>> {
}
package "Other Repositories" <<Rectangle>> {
}
MainScreen ..> "Other Screens"
"Other Screens" "*"<..>"*" "Other ViewModels"
"Other ViewModels" "*"<..>"*" "Other Repositories"

@enduml